name: gestion_entrega_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cubixd: ^0.1.1
  dio: ^5.4.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_image_slideshow: ^0.1.6
  flutter_multi_formatter: ^2.12.4
  flutter_polyline_points: ^2.0.0
  fluttertoast: ^8.2.4
  geocode: ^1.0.3
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  location: ^5.0.3
  lottie: ^2.7.0
  sn_progress_dialog: ^1.1.3
  url_launcher: ^6.2.4
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/json/
    
flutter_native_splash:
  color: "#f44336"
  image: assets/img/logo.png
  android_12:
    image: assets/img/logo.png
    color: "#f44336"