name: gestion_entrega_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  location: ^5.0.3
  flutter_image_slideshow: ^0.1.6
  geocode: ^1.0.3
  flutter_multi_formatter: ^2.12.4
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  lottie: ^2.7.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/json/
